### ISSUE TITLE
BSTextDemo会崩溃

### ISSUE THREAD

**Issue by LongChLiu** [a1049145827/BSText#11]
BSTextDemo中，点击Text Attachments，时而会崩溃

![屏幕快照 2020-02-18 下午11 49 03](https://user-images.githubusercontent.com/10141615/74752159-39268d80-52a9-11ea-9be3-08ccf4331c81.png)

![屏幕快照 2020-02-18 下午11 47 38](https://user-images.githubusercontent.com/10141615/74752101-2449fa00-52a9-11ea-91a5-05967e8d99ba.png)

**Comment by LongChLiu** [comment]
public class TextRunDelegate: NSObject, NSCopying, NSCoding, NSSecureCoding {
    
    var userInfo: NSMutableDictionary?
    @objc public var ascent: CGFloat = 0
    @objc public var descent: CGFloat = 0
    @objc public var width: CGFloat = 0
    
    @objc public var ctRunDelegate: CTRunDelegate {
        
        get {
            // MARK: - 此处要使用本类对象，否则之后需要取出 Delegate 的 ConRef 的时候会出问题
            let extentBuffer = UnsafeMutablePointer<TextRunDelegate>.allocate(capacity: 1)
            if self.descent > 0 {
                extentBuffer.pointee = self
            } else {
                extentBuffer.pointee = self.copy() as! TextRunDelegate
            }
            

行 extentBuffer.pointee = self 处，闪退

**Comment by NiuDongYue** [comment]
我也遇到了相同的问题，有解决办法了吗？

**Comment by a1049145827** [comment]
这个问题感觉跟 Swift 语言或者 iOS 系统的版本有关系，请各位反馈问题的时候附带一下 Xcode 版本，真机/模拟器版本，Swift 版本等信息，谢谢。

**Comment by libing1125** [comment]
xcode11.3.3 iphone11

**Comment by magicer0126** [comment]
> 公共类TextRunDelegate：NSObject，NSCopying，NSCoding，NSSecureCoding {
> 
> ```
> var userInfo: NSMutableDictionary?
> @objc public var ascent: CGFloat = 0
> @objc public var descent: CGFloat = 0
> @objc public var width: CGFloat = 0
> 
> @objc public var ctRunDelegate: CTRunDelegate {
>     
>     get {
>         // MARK: - 此处要使用本类对象，否则之后需要取出 Delegate 的 ConRef 的时候会出问题
>         let extentBuffer = UnsafeMutablePointer<TextRunDelegate>.allocate(capacity: 1)
>         if self.descent > 0 {
>             extentBuffer.pointee = self
>         } else {
>             extentBuffer.pointee = self.copy() as! TextRunDelegate
>         }
> ```
> 
> 行extentBuffer.pointee =自我处，闪退

在给`UnsafeMutablePointer`类型赋值`pointee`时，需要调用方法，`initialize`方法，设置 pointee 的值。
```
extentBuffer.initialize(to: self)
```

**Comment by a1049145827** [comment]
此问题已修复
