### ISSUE TITLE
使用自动布局会crash

### ISSUE THREAD

**Issue by jaychen04** [a1049145827/BSText#4]
使用自动布局crash，demo中改成 override func viewWillLayoutSubviews() {
textView.size = view.size
}就会复现

**Comment by jaychen04** [comment]
使用自动布局crash，demo中改成  override func viewWillLayoutSubviews() {
        textView.size = view.size
    }就会复现

**Comment by a1049145827** [comment]
请问现在是否能够复现这个问题呢？
